# Generated by Django 3.0.7 on 2022-10-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20221009_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='first_name',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
